name: Build and Push Image

env:
  IMAGE_NAME: ghcr.io/leifetter/abipulli-backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Build Arm64 image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        platforms: linux/arm64
        tags: ${{ env.IMAGE_NAME }}:test-only
        build-args: |
          NODE_ENV=production
          VITE_API_URL=https://api.etter.app
